### ISSUE TITLE
RuntimeError: Gtk couldn't be initialized

### ISSUE THREAD

**Issue by yochananmarqos** [ahoneybun/keyboard-color-switcher#47]
Running from the latest commit using my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/keyboard-color-switcher-git):

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 116, in <module>
    win = MainWindow()
  File "/usr/lib/python3.10/site-packages/keyboard-color-switcher/keyboard-color-switcher.py", line 34, in __init__
    Gtk.Window.__init__(self)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

I haven't built or run it in awhile, so I'm not sure if it's related to Python 3.10 or not.

Serval WS (serw12)
Manjaro GNOME
`gtk3` 3.24.31
`python` 3.10.1
`python-gobject` 3.42.0

**Comment by yochananmarqos** [comment]
@JeffLabonte Any ideas about this?
